const tasks = [
  {
    id: 1,
    title: "Set up environment",
    description: "Install Node.js, npm, and git",
    completed: true,
    created_at: "2025-05-28T07:21:39.161Z",
    priority: "",
  },
  {
    id: 2,
    title: "Create a new project",
    description: "Create a new project using the Express application generator",
    completed: true,
    created_at: "2025-05-27T07:21:39.161Z",
    priority: "medium",
  },
  {
    id: 3,
    title: "Install nodemon",
    description: "Install nodemon as a development dependency",
    completed: true,
    created_at: "2025-05-26T07:21:39.161Z",
    priority: "high",
  },
  {
    id: 4,
    title: "Install Express",
    description: "Install Express",
    completed: false,
    created_at: "2025-05-28T07:22:39.161Z",
    priority: "low",
  },
  {
    id: 5,
    title: "Install Mongoose",
    description: "Install Mongoose",
    completed: false,
    created_at: "2025-05-29T07:18:39.161Z",
    priority: "low",
  },
  {
    id: 6,
    title: "Install Morgan",
    description: "Install Morgan",
    completed: false,
    created_at: "2025-05-29T07:17:39.161Z",
    priority: "high",
  },
  {
    id: 7,
    title: "Install body-parser",
    description: "Install body-parser",
    completed: false,
    created_at: "2025-05-29T07:16:39.161Z",
    priority: "medium",
  },
  {
    id: 8,
    title: "Install cors",
    description: "Install cors",
    completed: false,
    created_at: "2025-05-29T07:24:39.161Z",
    priority: "high",
  },
  {
    id: 9,
    title: "Install passport",
    description: "Install passport",
    completed: false,
    created_at: "2025-05-29T07:11:39.161Z",
    priority: "low",
  },
  {
    id: 10,
    title: "Install passport-local",
    description: "Install passport-local",
    completed: false,
    created_at: "2025-05-29T07:21:39.161Z",
    priority: "medium",
  },
  {
    id: 11,
    title: "Install passport-local-mongoose",
    description: "Install passport-local-mongoose",
    completed: false,
    created_at: "2025-05-29T07:11:39.161Z",
    priority: "low",
  },
  {
    id: 12,
    title: "Install express-session",
    description: "Install express-session",
    completed: false,
    created_at: "2025-05-29T07:21:34.161Z",
    priority: "high",
  },
  {
    id: 13,
    title: "Install connect-mongo",
    description: "Install connect-mongo",
    completed: false,
    created_at: "2025-05-29T07:21:32.161Z",
    priority: "medium",
  },
  {
    id: 14,
    title: "Install dotenv",
    description: "Install dotenv",
    completed: false,
    created_at: "2025-05-29T08:21:39.161Z",
    priority: "low",
  },
  {
    id: 15,
    title: "Install jsonwebtoken",
    description: "Install jsonwebtoken",
    completed: false,
    created_at: "2025-05-29T09:21:39.161Z",
    priority: "high",
  },
];

module.exports = { tasks };
